apiVersion: v1
kind: Pod
metadata:
  name: cryptocurrencyapi
  labels:
    name: cryptocurrencyapi
spec:
  containers:
    - name: cryptocurrencyapi
      image: ozguryesilbas/cryptocurrency
      ports:
        - containerPort: 8080