apiVersion: v1
kind: Pod
metadata:
  name: cryptocurrency-pod
  labels:
    name: cryptocurrency-pod
spec:
  containers:
    - name: cryptocurrency-pod
      image: ozguryesilbas/cryptocurrency
      ports:
        - containerPort: 8080